# Generated by Django 4.2.7 on 2024-01-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_myuser_admission_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='post',
        ),
    ]
