# Generated by Django 4.2.7 on 2023-12-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('post_name', models.CharField(max_length=100)),
                ('post_content', models.TextField()),
            ],
        ),
    ]
