# Generated by Django 4.2.7 on 2024-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_post_post_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_by_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
